### ISSUE TITLE
What are .tag files

### ISSUE THREAD

**Issue by pchaigno** [OmarBenitez/CL-Cinema#1]
Hi there!

We are working, at [Linguist](https://github.com/linguist), on syntax highlighting for `.tag` files on github.com.
I'm trying to figure out what [these `.tag` files](https://github.com/OmarBenitez/CL-Cinema/search?utf8=%E2%9C%93&q=extension%3Atag) are exactly. Could you give me some insight on this?

Cheers

**Comment by OmarBenitez** [comment]
It was my mistake upload these .tag files.
but, in fact, they are files based on Groovy basically and embedded Java. I'm working with PlayFramework and their modules works with these to compile.

**Comment by pchaigno** [comment]
Okay. Thank you!
